import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Navbar from "@/components/Navbar/Navbar"
import { Providers } from "./providers"

const ubuntu = localFont({
	src: [
		{
			path: "../../public/fonts/Ubuntu-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/Ubuntu-Italic.ttf",
			weight: "400",
			style: "italic",
		},
		{
			path: "../../public/fonts/Ubuntu-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../../public/fonts/Ubuntu-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../../public/fonts/Ubuntu-Light.ttf",
			weight: "300",
			style: "normal",
		},
	],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${ubuntu.className} bg-neutral-100 dark:bg-stone-800`}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	)
}
