import type { Metadata } from "next"
import { Ubuntu } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar/Navbar"
import { Providers } from "./providers"

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["300", "400", "500", "700"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${ubuntu.className} bg-neutral-100 dark:bg-stone-800`}>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	)
}
